### ISSUE TITLE
ledger process block may case painc when call map "checkBlockFns" 

### ISSUE THREAD

**Issue by zengchen221** [qlcchain/go-qlc#333]
### Issue-Type
- [x] bug report
- [ ] feature request
- [ ] Documentation improvement

### Checklist
- [ ] Running latest version of code.
- [ ] This issue has not been reported earlier.

### Your environment
* OS
* Go version
* Release tag/commit of the code

### Expected behavior
What should happen?

### Actual behavior
What is actually happening?

### Steps to reproduce
1. Provide detailed steps
2. how to reproduce this issue

### Any extra info ( for eg. code snippet to reproduce, logs, etc. )
```
2019-05-15T03:02:45.226056389Z ERROR [rpcServer] rpc/server.go:134 goroutine 2602058 [running]:
github.com/qlcchain/go-qlc/rpc.(*Server).serveRequest.func1(0xc0002cfaa0, 0x14e6000, 0xc00139aaa0)
	/qlcchain/go-qlc/rpc/server.go:133 +0x100
panic(0xfc0c00, 0x1ca9950)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/qlcchain/go-qlc/ledger/process.(*LedgerVerifier).BlockCheck(0xc0002640f0, 0x14d4300, 0x0, 0xc00224df00, 0x2b, 0x2b)
	/qlcchain/go-qlc/ledger/process/ledger_processor.go:63 +0x1c0
github.com/qlcchain/go-qlc/ledger/process.(*LedgerVerifier).Process(0xc0002640f0, 0x14d4300, 0x0, 0x5176c2, 0xc00ae59230, 0xc002811520)
	/qlcchain/go-qlc/ledger/process/ledger_processor.go:52 +0x43
github.com/qlcchain/go-qlc/rpc/api.(*LedgerApi).Process(0xc000262a40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/qlcchain/go-qlc/rpc/api/ledger.go:618 +0x70
reflect.Value.call(0xc0004753e0, 0xc0001106c0, 0x13, 0x10f04d0, 0x4, 0xc0129f9b00, 0x2, 0x2, 0x2, 0xc0129f9b00, ...)
	/usr/local/go/src/reflect/value.go:447 +0x461
reflect.Value.Call(0xc0004753e0, 0xc0001106c0, 0x13, 0xc0129f9b00, 0x2, 0x2, 0x1, 0x1, 0x0)
	/usr/local/go/src/reflect/value.go:308 +0xa4
```

**Comment by pwc5232759** [comment]
Still not solved
